title: Antares Chen
email: antaresc@uchicago.edu
description: "A personal website for Antares Chen"
permalink: ':title/'
baseurl: ""
url: "https://antaresc.github.io"

# Contact links
email: antaresc@uchicago.edu
website: antaresc.github.io
github: antaresc
facebook:
instagram:
pinterest:

# Newsletter
mailchimp:

# Disqus
discus_identifier:

# Tracker
analytics:

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-feed

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
